# Generated by Django 5.1.4 on 2025-02-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0476_facility_default_internal_organization_and_more'),
        ('hcx', '0011_coverage_coverageeligibilityrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverageeligibilityrequest',
            name='encounter',
        ),
        migrations.AlterField(
            model_name='coverageeligibilityrequest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility'),
        ),
    ]
