# Generated by Django 5.1.4 on 2025-02-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0011_claimrequest_claimresponse_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcx.claimrequest'),
        ),
    ]
