# Generated by Django 5.1.4 on 2025-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0012_remove_coverageeligibilityrequest_encounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='kind',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='period',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='policy_holder',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='relationship',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='subscriber',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverageeligibilityresponse',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
