# Generated by Django 5.1.4 on 2025-02-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0013_alter_coverage_kind_alter_coverage_period_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claim',
            table='claim_deprecated',
        ),
        migrations.AlterModelTable(
            name='communication',
            table='communication_deprecated',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='policy_deprecated',
        ),
    ]
