# Generated by Django 5.1.4 on 2025-02-13 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0476_facility_default_internal_organization_and_more'),
        ('hcx', '0014_alter_claim_table_alter_communication_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claim',
            new_name='ClaimDeprecated',
        ),
        migrations.RenameModel(
            old_name='Communication',
            new_name='CommunicationDeprecated',
        ),
        migrations.RenameModel(
            old_name='Policy',
            new_name='PolicyDeprecated',
        ),
    ]
