# Generated by Django 5.1.4 on 2025-02-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0015_rename_claim_claimdeprecated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimdeprecated',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='communicationdeprecated',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='policydeprecated',
            options={'managed': False},
        ),
    ]
