# Generated by Django 5.1.4 on 2025-02-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0018_alter_claimdeprecated_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimdeprecated',
            options={'managed': False},
        ),
    ]
