# Generated by Django 5.1.4 on 2025-02-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0019_alter_claimdeprecated_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimdeprecated',
            options={'managed': True},
        ),
    ]
