# Generated by Django 5.1.4 on 2025-02-13 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0020_alter_claimdeprecated_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdeprecated',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_deprecated_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
