# Generated by Django 5.1.4 on 2025-02-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcx', '0022_claim_claimresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimresponse',
            name='total',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
